// <auto-generated />
namespace SDS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateemployeedb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateemployeedb));
        
        string IMigrationMetadata.Id
        {
            get { return "202401310658267_update-employee-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
